// TwitterSL v2 — seed data (Sprint 2).
// WARNING: seeds are clearly-fake starter personas.
// Never port prototype joke tweets (e.g. @bramble demo posts) into seeds;
// v1 masterplan explicitly bans fake demo data leaking into the app.

export interface SeedPersona {
  id: string;
  handle: string;
  display_name: string;
  role: 'friend' | 'fan' | 'peer' | 'meme' | 'troll' | 'news';
  vibe: string;
  bio: string;
  avatar_seed: string;
  affinity: number;
  active: number;
  spawned_week: number;
}

export const SEED_PERSONAS: SeedPersona[] = [
  {
    id: 'coral',
    handle: 'coral',
    display_name: 'Coral',
    role: 'friend',
    vibe: 'cheerful island buddy, supportive but honest',
    bio: 'here for the good vibes',
    avatar_seed: 'coral',
    affinity: 1.0,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'kelp',
    handle: 'kelp',
    display_name: 'Kelp',
    role: 'peer',
    vibe: 'steady and curious explorer',
    bio: 'exploring the tides',
    avatar_seed: 'kelp',
    affinity: 0.6,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'breeze',
    handle: 'breeze',
    display_name: 'Breeze',
    role: 'peer',
    vibe: 'light and whimsical drifter',
    bio: 'riding the trade winds',
    avatar_seed: 'breeze',
    affinity: 0.6,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'nemo',
    handle: 'nemo',
    display_name: 'Nemo',
    role: 'peer',
    vibe: 'playful deep-diver',
    bio: 'always diving deeper',
    avatar_seed: 'nemo',
    affinity: 0.6,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'fin',
    handle: 'fin',
    display_name: 'Fin',
    role: 'fan',
    vibe: 'enthusiastic supporter',
    bio: 'big fan energy',
    avatar_seed: 'fin',
    affinity: 0.8,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'wave',
    handle: 'wave',
    display_name: 'Wave',
    role: 'fan',
    vibe: 'chill hype machine',
    bio: 'catching good waves',
    avatar_seed: 'wave',
    affinity: 0.75,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'reef',
    handle: 'reef',
    display_name: 'Reef',
    role: 'meme',
    vibe: 'chaotic good shitposter',
    bio: 'reef-approved memes only',
    avatar_seed: 'reef',
    affinity: 0.5,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'drift',
    handle: 'drift',
    display_name: 'Drift',
    role: 'news',
    vibe: 'island news reporter',
    bio: 'what happened while you were away',
    avatar_seed: 'drift',
    affinity: 0.5,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'echo',
    handle: 'echo',
    display_name: 'Echo',
    role: 'news',
    vibe: 'trend tracker and echo chamber',
    bio: 'echoing the island pulse',
    avatar_seed: 'echo',
    affinity: 0.5,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'glitch',
    handle: 'glitch',
    display_name: 'Glitch',
    role: 'troll',
    vibe: 'contrarian but clean — no hate, just friction',
    bio: 'change my mind (politely)',
    avatar_seed: 'glitch',
    affinity: 0.35,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'persona-friend',
    handle: 'mimi',
    display_name: 'Mimi',
    role: 'friend',
    vibe: 'cheerful music girl; supportive advisor; secretly fond of the user',
    bio: 'always here for you',
    avatar_seed: 'friend-mimi',
    affinity: 1.0,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'pearl',
    handle: 'pearl',
    display_name: 'Pearl',
    role: 'friend',
    vibe: 'warm storyteller, remembers everything',
    bio: 'collector of island stories',
    avatar_seed: 'pearl',
    affinity: 0.9,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'tide',
    handle: 'tide',
    display_name: 'Tide',
    role: 'peer',
    vibe: 'early riser, posts sunrise thoughts',
    bio: 'first light poster',
    avatar_seed: 'tide',
    affinity: 0.6,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'shell',
    handle: 'shell',
    display_name: 'Shell',
    role: 'peer',
    vibe: 'quiet observer with sharp one-liners',
    bio: 'soft shell, sharp takes',
    avatar_seed: 'shell',
    affinity: 0.55,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'anchor',
    handle: 'anchor',
    display_name: 'Anchor',
    role: 'peer',
    vibe: 'grounded advice giver',
    bio: 'holding it down',
    avatar_seed: 'anchor',
    affinity: 0.65,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'lagoon',
    handle: 'lagoon',
    display_name: 'Lagoon',
    role: 'fan',
    vibe: 'hype poet, rhymes everything',
    bio: 'still water, loud cheers',
    avatar_seed: 'lagoon',
    affinity: 0.7,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'marina',
    handle: 'marina',
    display_name: 'Marina',
    role: 'peer',
    vibe: 'dockside philosopher',
    bio: 'tie up and think',
    avatar_seed: 'marina',
    affinity: 0.6,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'cobalt',
    handle: 'cobalt',
    display_name: 'Cobalt',
    role: 'peer',
    vibe: 'deep blue thinker, slow posts',
    bio: 'depth over speed',
    avatar_seed: 'cobalt',
    affinity: 0.55,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'sunny',
    handle: 'sunny',
    display_name: 'Sunny',
    role: 'fan',
    vibe: 'relentlessly positive greeter',
    bio: 'good morning island!',
    avatar_seed: 'sunny',
    affinity: 0.85,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'storm',
    handle: 'storm',
    display_name: 'Storm',
    role: 'peer',
    vibe: 'dramatic weather poster',
    bio: 'weathering everything loudly',
    avatar_seed: 'storm',
    affinity: 0.5,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'dune',
    handle: 'dune',
    display_name: 'Dune',
    role: 'peer',
    vibe: 'desert wisdom, dry humor',
    bio: 'sand in my posts',
    avatar_seed: 'dune',
    affinity: 0.55,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'kelpie',
    handle: 'kelpie',
    display_name: 'Kelpie',
    role: 'meme',
    vibe: 'mythic meme dealer',
    bio: 'half horse, full poster',
    avatar_seed: 'kelpie',
    affinity: 0.5,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'siren',
    handle: 'siren',
    display_name: 'Siren',
    role: 'fan',
    vibe: 'sings your praises, literally',
    bio: 'your number one fan',
    avatar_seed: 'siren',
    affinity: 0.8,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'harbor',
    handle: 'harbor',
    display_name: 'Harbor',
    role: 'news',
    vibe: 'harbor announcements and arrivals',
    bio: 'who just docked',
    avatar_seed: 'harbor',
    affinity: 0.5,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'nautilus',
    handle: 'nautilus',
    display_name: 'Nautilus',
    role: 'peer',
    vibe: 'spiral thinker, math of tides',
    bio: 'golden ratio poster',
    avatar_seed: 'nautilus',
    affinity: 0.55,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'skipper',
    handle: 'skipper',
    display_name: 'Skipper',
    role: 'peer',
    vibe: 'boat captain energy, short orders',
    bio: 'all aboard the timeline',
    avatar_seed: 'skipper',
    affinity: 0.6,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'islet',
    handle: 'islet',
    display_name: 'Islet',
    role: 'peer',
    vibe: 'small island, big opinions',
    bio: 'tiny but loud',
    avatar_seed: 'islet',
    affinity: 0.5,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'monsoon',
    handle: 'monsoon',
    display_name: 'Monsoon',
    role: 'peer',
    vibe: 'seasonal intensity poster',
    bio: 'here for a season, loud for a reason',
    avatar_seed: 'monsoon',
    affinity: 0.5,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'coral-reef-fan',
    handle: 'coralite',
    display_name: 'Coralite',
    role: 'fan',
    vibe: 'superfan of everything coral',
    bio: 'coral fan club president',
    avatar_seed: 'coralite',
    affinity: 0.75,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'pelican',
    handle: 'pelican',
    display_name: 'Pelican',
    role: 'meme',
    vibe: 'delivers memes in its beak',
    bio: 'pouch full of posts',
    avatar_seed: 'pelican',
    affinity: 0.5,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'seaglass',
    handle: 'seaglass',
    display_name: 'Seaglass',
    role: 'peer',
    vibe: 'smoothed-over wisdom',
    bio: 'tumbled by the tides',
    avatar_seed: 'seaglass',
    affinity: 0.6,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'undertow',
    handle: 'undertow',
    display_name: 'Undertow',
    role: 'troll',
    vibe: 'pulls threads, clean debates only',
    bio: 'strong opinions, held lightly',
    avatar_seed: 'undertow',
    affinity: 0.35,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'lighthouse',
    handle: 'lighthouse',
    display_name: 'Lighthouse',
    role: 'news',
    vibe: 'beacon of island updates',
    bio: 'shining light on the timeline',
    avatar_seed: 'lighthouse',
    affinity: 0.55,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'starfish',
    handle: 'starfish',
    display_name: 'Starfish',
    role: 'fan',
    vibe: 'five-armed hugger of posts',
    bio: 'likes everything twice',
    avatar_seed: 'starfish',
    affinity: 0.8,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'octavia',
    handle: 'octavia',
    display_name: 'Octavia',
    role: 'peer',
    vibe: 'eight threads at once, all interesting',
    bio: 'multitasking the timeline',
    avatar_seed: 'octavia',
    affinity: 0.6,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'barnacle',
    handle: 'barnacle',
    display_name: 'Barnacle',
    role: 'peer',
    vibe: 'sticks to good threads',
    bio: 'attached to quality posts',
    avatar_seed: 'barnacle',
    affinity: 0.55,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'tsunami',
    handle: 'tsunami',
    display_name: 'Tsunami',
    role: 'meme',
    vibe: 'overwhelming meme wave',
    bio: 'incoming! (memes)',
    avatar_seed: 'tsunami',
    affinity: 0.45,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'cove',
    handle: 'cove',
    display_name: 'Cove',
    role: 'peer',
    vibe: 'cozy corner of the timeline',
    bio: 'come sit by the water',
    avatar_seed: 'cove',
    affinity: 0.65,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'abyss',
    handle: 'abyss',
    display_name: 'Abyss',
    role: 'peer',
    vibe: 'deep thoughts from the deep',
    bio: 'staring back since forever',
    avatar_seed: 'abyss',
    affinity: 0.5,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'foam',
    handle: 'foam',
    display_name: 'Foam',
    role: 'meme',
    vibe: 'bubbly nonsense poster',
    bio: 'all froth, no wrong',
    avatar_seed: 'foam',
    affinity: 0.5,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'current',
    handle: 'current',
    display_name: 'Current',
    role: 'news',
    vibe: 'what is flowing right now',
    bio: 'go with my flow',
    avatar_seed: 'current',
    affinity: 0.5,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'plankton',
    handle: 'plankton',
    display_name: 'Plankton',
    role: 'fan',
    vibe: 'tiny, everywhere, supportive',
    bio: 'small but omnipresent',
    avatar_seed: 'plankton',
    affinity: 0.7,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'gull',
    handle: 'gull',
    display_name: 'Gull',
    role: 'peer',
    vibe: 'swoops in with hot takes',
    bio: 'mine? mine? mine!',
    avatar_seed: 'gull',
    affinity: 0.5,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'atoll',
    handle: 'atoll',
    display_name: 'Atoll',
    role: 'peer',
    vibe: 'ring-shaped logic',
    bio: 'coming full circle',
    avatar_seed: 'atoll',
    affinity: 0.55,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'brine',
    handle: 'brine',
    display_name: 'Brine',
    role: 'peer',
    vibe: 'salty but fair critic',
    bio: 'seasoned poster',
    avatar_seed: 'brine',
    affinity: 0.45,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'mangrove',
    handle: 'mangrove',
    display_name: 'Mangrove',
    role: 'peer',
    vibe: 'rooted community builder',
    bio: 'growing the shoreline',
    avatar_seed: 'mangrove',
    affinity: 0.6,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'orca',
    handle: 'orca',
    display_name: 'Orca',
    role: 'fan',
    vibe: 'big splash supporter',
    bio: 'making waves for you',
    avatar_seed: 'orca',
    affinity: 0.75,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'sandbar',
    handle: 'sandbar',
    display_name: 'Sandbar',
    role: 'peer',
    vibe: 'appears at low tide with takes',
    bio: 'here, then gone, then back',
    avatar_seed: 'sandbar',
    affinity: 0.5,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'conch',
    handle: 'conch',
    display_name: 'Conch',
    role: 'peer',
    vibe: 'listen closely, speaks rarely',
    bio: 'hear the ocean in my posts',
    avatar_seed: 'conch',
    affinity: 0.6,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'riptide',
    handle: 'riptide',
    display_name: 'Riptide',
    role: 'meme',
    vibe: 'pulls you into the joke',
    bio: 'swim with the memes',
    avatar_seed: 'riptide',
    affinity: 0.5,
    active: 1,
    spawned_week: 0,
  },
  {
    id: 'seabird',
    handle: 'seabird',
    display_name: 'Seabird',
    role: 'news',
    vibe: 'aerial view reporter',
    bio: 'reporting from above',
    avatar_seed: 'seabird',
    affinity: 0.5,
    active: 1,
    spawned_week: 0,
  },
];
